name: Generate Snake

on:
  schedule: # every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: Arslan2003
          outputs: dist/snake.svg

      - name: Push Snake to Output Branch
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate snake"
          add: "dist/snake.svg"
          branch: output
